const campeones = { // [Q, W, E, R] | PARA CAMPEONES QUE SE CONVIERTEN  -->> [Q, W, E, R, Q, W, E],
    // ACTUALIZADO HASTA PARCHE 10.11.
    Aatrox : [14, 26, 9, 120],
    Ahri : [7, 9, 12, 130],
    Akali : [1.5, 20, 16, 100],
    Alistar : [17, 14, 12, 120],
    Amumu : [10, 1, 10, 150],
    Anivia : [10, 17, 4, 6],
    Annie : [4, 8, 14, 120],
    Aphelios : [],                        // REVISAR 
    Ashe : [0, 14, 90, 100],
    "Aurelion Sol" : [11, 8, 80, 110],
    Azir : [15, 8, 19 , 120],
    Bardo : [11, 14, 22, 110],
    Blitzcrank : [20, 15, 9 , 60],
    Brand : [8, 10, 10, 105],
    Braum : [10, 12, 18, 140],
    Caitlyn : [10, 30, 16, 90],
    Camille : [9, 15, 16, 140],
    Cassiopeia : [3.5, 24, 0.75, 120],
    "ChoGath": [7, 13, 7, 80],
    Corki : [8, 20, 16, 12],
    Darius : [9, 7, 24, 120],
    Diana : [8, 15, 22, 100],
    "Dr Mundo" : [4, 4, 6, 110],
    Draven : [12, 12, 18, 120],
    Ekko : [9, 22, 9, 110],
    Elise : [6, 12, 12, 4, 6, 10, 22],
    Evelynn : [8, 15, 8, 140],
    Ezreal: [5.5, 12, 25, 120],
    Fiddlesticks : [15, 9, 10, 140],
    Fiora : [16, 24, 11, 110],
    Fizz : [8, 7, 16, 100],
    Galio : [12, 16, 12, 200],
    Gangplank : [5, 22, 17, 180],
    Garen : [8, 23, 9, 120],
    Gnar : [20, 7, 22, 90],
    Gragas : [11, 5, 16, 120],
    Graves : [12, 26, 18, 120],
    Hecarim : [4, 22, 20, 140],
    Heimerdinger : [20, 11, 12, 100],
    Illaoi : [10, 4, 16, 120],
    Irelia : [12, 20, 18, 140],
    Ivern : [14, 40, 12, 140],
    Ianna : [12, 8, 16, 150],
    "Jarvan IV" : [10, 12, 12, 120],
    Jax : [8, 7, 16, 80],
    Jayce : [16, 10, 20, 6, 8, 13, 16],
    Jhin : [7, 12, 28, 120],
    Jinx : [0.9, 8, 24, 90],
    "KaiSa" : [8, 22, 16, 110],
    Kalista : [8, 90, 14, 150],
    Karma : [7, 12, 10 , 45],
    Karthus : [1, 18, 0.5, 200],
    Kassadin : [11, 7, 5, 5],
    Katarina : [11, 15, 14, 90],
    Kayle : [12, 15, 8 , 160],
    Kayn : [6, 13, 21, 120],
    Kennen : [8, 14, 10, 120],
    "KhaZix" : [4, 9, 20, 100],
    Kindred : [9, 18, 16, 180],
    Kled : [11, 14, 14, 160],
    "KogMaw" : [8, 17, 12, 2],
    LeBlanc : [6, 18, 14, 60],
    "Lee Sin" : [11, 12, 10, 110],
    Leona : [5, 114, 12, 90],
    Lissandra : [8, 14, 24, 120],
    Lucian : [9, 14, 22, 110],
    Lulu : [7, 16, 8, 110],
    Lux : [11, 14, 10, 80],
    Malphite : [8, 12, 7, 130],
    Malzahar : [6, 8, 15, 140],
    Maokai : [8, 13, 10, 120],
    "Master Yi" : [18, 28, 18, 85],
    "Miss Fortune" : [7, 12, 18, 120],
    Mordekaiser : [9, 14, 24, 140],
    Morgana : [11, 12, 26, 120],
    Nami : [12, 10, 11, 120],
    Nasus : [8, 15, 12, 120],
    Nautilus : [14, 12, 7, 120],
    Neeko : [7, 20 , 12, 90],
    Nidalee : [6, 13, 12, 3, 6, 6, 6],
    Nocturne : [10, 20, 15, 150],
    Nunu : [12, 14, 14, 110],
    Olaf : [7, 16, 11, 100],
    Orianna : [6, 7, 9, 110],
    Ornn : [9, 12, 16, 140],
    Pantheon : [10, 13, 22, 180],
    Poppy : [8, 24, 14, 140],
    Pyke : [12, 12, 15, 120],
    Qiyana : [7, 7, 12, 120],
    Quinn : [11, 50, 12, 0], // DUDA CON EL CD DE LA R.
    Rakan : [12, 18, 20, 130],
    Rammus : [16, 6, 12, 100],
    "RekSai" : [4, 4, 12, 100, 12, 10, 26],
    Renekton : [8, 13, 18, 120],
    Rengar : [6, 16, 10, 110],
    Riven : [13, 11, 12, 120],
    Rumble : [10, 6, 6, 100],
    Ryze : [6, 13, 3.25, 210],
    Sejuani : [20, 9, 1.5, 120],
    Senna : [15, 11, 26, 160],
    Sett : [9, 18, 16, 120],
    Shaco : [12, 16, 8, 100],
    Shen : [8, 18, 18, 200],
    Shyvana : [9, 12, 12, 0], //DUDA CON EL CD DE LA R
    Singed : [0, 17, 10, 120],
    Sion : [10, 15, 12, 140],
    Sivir : [7, 12, 22, 120],
    Skarner : [3.5, 13, 14, 120],
    Sona : [8, 10, 12, 140],
    Soraka : [8, 6, 20, 160],
    Swain : [10, 22, 13, 120],
    Sylas : [10, 13 , 14, 100],
    Syndra : [4, 12, 18, 120],
    "Tahm Kench" : [5, 20, 6, 140],
    Taliyah : [7, 16, 16, 180],
    Talon : [8, 9, 2, 100],
    Taric : [3, 15, 17, 180],
    Teemo : [8, 17, 0, 30],
    Thresh : [20, 22, 9, 140],
    Tristana : [20, 22, 16, 120],
    Trundle : [4, 15, 24, 120],
    Tryndamere : [12, 14, 12, 110],
    "Twisted Fate" : [6, 6, 0, 180],
    Twitch : [16, 13, 12, 90],
    Udyr : [6, 6 , 6, 6],
    Urgot : [12, 12, 16, 100],
    Varus : [18, 40, 18, 130],
    Vayne : [4, 0, 20, 100],
    Veigar : [7, 8, 18, 120],
    "VelKoz" : [7, 19, 16, 120],
    Vi : [12, 0, 14, 120],
    Viktor : [9, 17, 12, 120],
    Vladimir : [9, 28, 13, 150],
    Volibear : [12, 18, 11, 100],
    Warwick : [6, 120, 15, 110],
    Wukong : [9, 20, 10, 120],
    Xayah : [10, 20, 12, 160],
    Xerath : [9, 14, 13, 130],
    "Xin Zhao" : [7, 12, 12, 120],
    Yasuo : [4, 26, 0.5, 80],
    Yorick : [7, 20, 12, 160],
    Yuumi : [13.5, 10, 25, 130],
    Zac : [15, 5, 24, 130],
    Zed : [6, 22, 5, 120],
    Ziggs : [6, 20, 16, 120],
    Zilean : [10, 14, 15, 120],
    Zoe : [8.5, 0.25, 20, 11],
    Zyra : [7, 20, 12, 110],
}

const tips = {
    Aatrox : "Passive cooldown reduces by 2 seconds when Aatrox hits an ability or an auto attack on a champion, or large monsters. Goes up to 4 seconds if Aatrox hits with the edge of The Darkin Blade.",
    Ahri : "Spirit Rush (R) can be recasted twice more at a 1 second static cooldown within 10 seconds of activation at no additional cost",
    Akali : "Akali has 2.5 seconds of cooldown before the second ultimate cast. W duration is 5/5.5/6/6.5/7. Breaking invisibility extends smoke duration by 2 seconds.",
    Alistar : "Passive: Once Triumph stacks are consumed, Alistar can gain new stacks.",
    Anivia : "Passive duration is 6 seconds.",
    Annie : "Annie's Q refunds half its CD (and 100% mana cost) when killing its target. Tibbers remains on the field as a controllable pet for up to 45 seconds.",
    Aphelios : "Not easy to track this champion's cds. Check https://leagueoflegends.fandom.com/wiki/Aphelios.",
    Ashe : "Ashe's E has 2 stacks. 5 seconds between them.",
    Azir : "Azir's W has 2 charges. 1.5 seconds between them. Also, if Azir hits an enemy champions with his E, he gets a W charge.",
    Brand : "Brand cannot stack Blaze (passive) more than once on enemies who have exploded in the past 4 seconds.",
    Caitlyn : "Traps duration (W) per spel rank : 30/35/40/45/50 seconds.",
    Corki : "1st passive spawns at 8 minutes. Corki has 60 seconds to use it once picked. R can store 7 stacks and there is a 2 second CD between each cast.",
    Darius : "If Noxian Guillotine (R) kills its target, Darius can recast the ability within the next 20 seconds at no additional cost. At R level 3, if R kills the target, its cooldown reduction resets completely.",
    Diana : "Diana marks enemies for 3 seconds with her Q. If she dashes (E) to a marked target, her E cooldown resets.",
    Draven : "When Draven catches his spinning axe, his W cooldown resets.",
    Ekko : "His passive cooldown is 5 seconds on the same target.",
    Evelynn : "Evelynn gains Demon Shade (Passive) after not taking damage from enemy champions or turrets for 1.5 seconds, or after 4 seconds of basic attacking or casting an ability. Gaining Demon Shade resets Whiplash's (E) cooldown and empowers the next cast.",
    Ezreal : "If his Q hits an enemy, all of Ezreal's ability cooldowns are refreshed by 1.5 seconds.",
    Fiddlesticks : "If Fiddlestick's W is fully channeled or all targets are slain, 60& of the remaining cooldown is refunded.",
    Fiora : "When Q hits, it refunds 60% of its cooldown",
    Fizz : "If Seastone Trident (W) kills its target, its cooldown is reduced to 1 second.",
    Galio : "His passive is affected by Cooldown Reduction. His W shield refreshes after 12 seconds undamaged.",
    GangPlank : "Destroying a Powder Keg (E) instantly readies Trial by Fire (Passive), and gains 30% movement speed for 2 seconds.",
    Gnar : "W's CD is Mega Gnar CD. After transforming back into mini, you can't stack rage for 15 seconds. Catching the boomerang while in mid-air refunds 40% of its maximum cooldown, while if caught at the end of its return flight, it refunds completely (Q).", 
    Gragas : "Body Slam's (E) cooldown is reduced by 3 seconds if Gragas hits an enemy.",
    Graves : "E cooldown is reduced by 0.5 seconds for every pellet impacting an enemy.",
    Hecarim : "If Hecarim damages at least one enemy with Rampage (Q), its base cooldown on subsequent casts are reduced by 1 for 8 seconds, stacking up to twice.",
    Heimerdinger : "Q has a 1 sec cooldown between each charges to use.",
    Illaoi : "For the duration of her R (8 seconds), her W CD is halved. Tentacles despawn after Illaoi has left the area for 30 seconds.",
    Irelia : "Q cooldown is refunded if the target was marked (Irelia can mark enemies either with E or Q) or dies.",
    Ivern : "The grove matures over 40sec at lvl 1, and 1 second at lvl 15. When fully matured, Ivern can interact with the camp again.",
    Janna : "If Janna slows or applies an airbone effect with an ability to an enemy champion, Eye of the Storm (E) cooldown is reduced by 20%",
    "Jarvan IV" : "Passive is on target CD, it has a 6 second cooldown on target.",
    Jax : "Jax has to wait at least 1 second before reactivating his E.",
    Jayce : "He can't level his R, instead, he has 6 levels in each Q W E.",
    Jhin : "2.5 seconds of reload time every 4th basic attack. Every 10 seconds, Jhin reloads automatically if not attacking.",
    KaiSa : "Her ultimate's shield lasts for 2 seconds. W evolved refunds 70% of CD against champions. KaiSa basic attacks reduce E cooldown by 0.5 seconds.",
    Kalista : "E resets its cooldown and refunds mana only if it kills at least one target.",
    Karma : "Mantra (R) has 4 ranks (lvl 1, 6, 11, 16). Karma reduces Mantra's cooldown by 2/3/4 seconds every time she damages an enemy champion with an ability, halved to 1/1.5/2 seconds on basic attacks.",
    Kassadin : "His ultimate stacks last for 15 seconds.",
    Katarina : "Whenever an enemy that got damaged by Katarina in the last 3 seconds dies, all her ability cooldowns are reduced by 15 seconds. Daggers last 4 seconds before disappearing.",
    Kennen : "If the stun is applied more than once within 6 seconds, its duration is reduced to 0.5 seconds.",
    KhaZix : "Evolved Q refunds 45% of its CD against isolated targets. Evolved E refunds 100% CD on enemy champions takedowns.",
    Kindred : "40 seconds CD on jungle monster. 75 seconds CD of marking a champion for the hunt. Targets successfully hunted cannot be targeted again for 4 minutes. Casting Q into W area reduces Q CD to 2 seconds.",
    Kled : "When you mount Skaarl, you have to wait 30s to mount it again. Mounting or dismounting resets Kled basic abilities CD except W. Q dismounted CD is 20 seconds to 7 seconds, scaling with level. He can have 2 stacks of Q with 3 second CD between 2 uses.",
    KogMaw : "Each subsequent R cast within the next 8 seconds cost additional mana.",
    LeBlanc : "LeBlanc has between 0.2 and 4 seconds to recast W.",
    "Lee Sin" : "After casting a base ability, Lee Sin has 3 seconds to get the second cast. W cooldown is reduced by 50% if the target is a champion.",
    Lucian : "W mark lasts 6 seconds. E cooldown is reduced by 1 second for each passive hits. (2 seconds against champions)",
    Lulu : "Using E transfers Pix to the target for 6 seconds.",
    Lux : "Passive mark lasts 6 seconds. E can last 5 seconds. Shield duration is 2.5 seconds.",
    Malphite : "His passive cooldown is 10/8/6 seconds on levels 1/7/13 respectively.",
    Malzahar : "His passive cooldown is 30/24/18/12 seconds on levels 1/6/11/16 respectively.",
    Maokai : "His passive cooldown is 30/25/20 seconds on levels 1/6/11 respectively.",
    "Master Yi" : "Basic attacks reduce Q cooldown by 1 second. Takedowns reduce Yi's cooldowns by 70%.",
    "Miss Fortune" : "Marking a new target with her passive reduces her W cooldown by 1.1/2 seconds (based on CDR).",
    Morgana : "If her passive procs, 5% of her W cooldown refunds.",
    Nasus: "Q cooldown is reduced a 50% while in R.",
    Nautilus : "Nautilus passive is 6 seconds in all levels. Also, if his Q hits a wall, it gets a 50% refund on cooldown.",
    Neeko : "Her passive CD is 25 seconds at level 1 and 10 seconds at level 16. Her W clone lasts for 3 seconds.",
    Nidalee : "Triggering Hunt (Passive) resets R cooldown if Nidalee is in human form. In cougar form, killing or dashing to a hunted target refunds W cooldown scaling with R rank 40% to 70%.",
    Nocturne : "Basic attacks reduce passive cooldown by 1 second, or 2 seconds vs champions. Nocturne's R darkness lasts for 6 seconds.",
    Nunu : "Nunu has 1 second cooldown between each E use.",
    Olaf : "If olaf pickes up his axe, he reduces his Q cooldown by 4.5 seconds. His E cooldown is reduced by 1 second every time he hits a basic attack.",
    Ornn : "Passive Masterwork allows to upgrade items. Auto item upgrade is at level 13. Allies upgrades are available at levels 14,15,16,17.",
    Pantheon : "Q fast cast refunds 50% of cooldown. R cooldown is reduced to 30 seconds if the channel is interrupted or canceled.",
    Poppy : "Her R cooldown is set to 30 seconds if canceled.",
    Pyke : "If an enemy dies in the X of Pyke's R, Pyke can recast his ultimate for 20 seconds.",
    Qiyana : "Gathering an element with W resets cooldown on Q. W also resets passive cooldown on all targets.",
    Quinn : "Passive cooldown is based on critical strike chance. R has a cast time of 2 seconds.",
    Rakan : "Passive cooldown is based on level (1-17). Damaging an enemy champion with a basic attack or ability reduces the cooldown of his passive by 1 second per champion hit. If his passive's shield is damaged but not destroyed, it regenerates 10% of its maximum value after being out of combat for 5 seconds.",
    RekSai : "Rek'Sai loses 20 fury per second if she hasn't generated any in the last 5 seconds. Also, her tunnels have on target cooldown: 10/8/6/4/2 seconds.",
    Renekton : "Passive: Renekton loses 4 fure per second if he didn't deal or take damage in the last 12 seconds. E: hitting an enemy champion allows Renekton to cast E a second time within the next 4 seconds.",
    Rengar : "Passive: bonus range lasts for 0.25 seconds upon exiting brush or stealth. All Ferocity stacks are lsot after being out of combat for 8 seconds.",
    Riven : "Q can be reactivated twice within the next 4 seconds, with the second cast refreshing the time. Riven can cast her second R within 15 seconds.",
    Rumble : "Passive: Rumble loses 10 heat per second after not using any ability for 4 seconds. Once overheated, heat decays back to 0 in 6 seconds. E: Rumble can store up to 2 charges.",
    Ryze : "Q: Ryze's other basic abilities reset Q's cooldown and charge a rune for 4 seconds, up to 2.",
    Sejuani : "Passive: Sejuani recieves her passive if she didn't take damage from monsters and enemy champions in the last 12 seconds. E: Enemy champions stunned by Sejuani cannot gain Frost again for 10/9/6 seconds.",
    Senna : "Passive is on target cooldown. Basic attacks reduce Q's cooldown by 1 second.",
    Shaco : "Passive has an on-target cooldown. Passive is reduced by CDR.",
    Shyvana : "Shyvana's basic attacks against non-structures reduce Q's cooldown by 0.5 seconds",
    Singed : "Passive has an on-target cooldown. R lasts for 25 seconds.",
    Skarner : "Basic attacks on non-structures reduce Q's cooldown by 0.25 seconds, quadrupled to 1 against enemy champions. Every time he stuns a target with E or suppresses an enemy with R, his E cooldown is reduced by the corresponding duration of the disable. Once captured, Crystal Spires are impposible to recapture for 15 seconds",
    Sona : "Base cooldown on basic abilities is reduced with R ranks: 10%/25%/40%",
    Swain : "Passive cooldown is static and dependes on level.",
    Sylas : "Passive can store 3 charges. Hijacked ultimate hold duration: 90 seconds.",
}